name: Run Selenium Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest

      - name: Download Chrome & chromedriver
        continue-on-error: true
        run: |
          sudo apt update || true
          sudo apt install -y --no-install-recommends wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb

          CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
          DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run pytest suite
        run: |
          pytest tests/test_samsung_homepage_logo_resilient.py --disable-warnings --maxfail=1 -v

      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-screenshots
          path: screenshots/
